
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: CoffeeInt
  username: postgres
  password: postgres
  host: db
  port: 5432

test:
  <<: *default
  database: CoffeeInt_test
  username: postgres
  password: postgres
  host: db
  port: 5432